### ISSUE TITLE
Curl error when trying to install via install_github

### ISSUE THREAD

**Issue by Maiae** [tidyverts/tsibblestats#6]
I get an error when trying to install `tsibblestats` using `install_github`
I have tried in different networks and got the same issue.

```
> devtools::install_github("tidyverts/tsibblestats")
Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed to connect to api.github.com port 80: Timed out
```

**Comment by mitchelloharawild** [comment]
Are you able to install any packages using devtools::install_github?

**Comment by Maiae** [comment]
No, perhaps this is a wide `devtools::install_github` or `curl` issue.
Closing it now.
